#!/bin/bash
set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Assume the project root is one level above (scripts/ is inside the project root)
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

echo "🔧 Cleaning up line breaks in .md files from the project root: $PROJECT_ROOT"

# Change to the project root so find uses relative paths
cd "$PROJECT_ROOT"

# Invisible character (zero-width space) used for control
INVISIBLE_CHAR=$(printf '\u200B')

# Directories to exclude (easy to modify)
EXCLUDE_DIRS=(
    "./book"
    "./.git"
    "./node_modules"
)

# Build the -not -path arguments for find
EXCLUDE_PATTERNS=()
for dir in "${EXCLUDE_DIRS[@]}"; do
    EXCLUDE_PATTERNS+=(-not -path "${dir}/*")
done

find . -name "*.md" "${EXCLUDE_PATTERNS[@]}" | while read -r file; do
    echo "   Processing: $file"

    # Use a secure temporary file (mktemp) to avoid conflicts
    tmp_file=$(mktemp)

    awk -v inv="$INVISIBLE_CHAR" '
    BEGIN {
        blank_count = 0
    }

    {
        # ---- 1. REMOVE ARTIFACTS FROM PREVIOUS RUNS ----

        # Remove invisible character
        gsub(inv, "", $0)

        # Remove trailing spaces/tabs
        gsub(/[[:space:]]+$/, "", $0)

        # Remove lines generated by previous executions of this script
        if ($0 == "&nbsp;<br>") {
            next
        }

        # ---- 2. HANDLE BLANK LINES ----

        if (length($0) == 0) {
            blank_count++

            # Keep at most 2 consecutive blank lines
            if (blank_count <= 2) {
                print ""
            }

            next
        }

        # ---- 3. NORMALIZE NON-BLANK LINES ----

        blank_count = 0

        # Ensure exactly 2 trailing spaces
        print $0 "  "
    }

    END {
        # ---- 4. APPEND 5 "&nbsp;<br>" LINES + INVISIBLE CHARACTER ----
        for (i = 1; i <= 5; i++) {
            print "&nbsp;<br>" inv
        }
    }
    ' "$file" > "$tmp_file" && mv "$tmp_file" "$file"

    # Remove the temporary file if something goes wrong (shouldn't happen, but just in case)
    rm -f "$tmp_file" 2>/dev/null || true

done

echo "✅ Cleanup completed!"